#This script configures OIM after domain creation

#!/usr/bin/env bash

source setenv.sh

unset DOMAIN_HOME



$ORACLE_HOME/bin/config.sh -debug -silent OIM_SERVER=true INSTALL_OIM_DESIGN_CONSOLE=true INSTALL_OIM_REMOTE_MANAGER=false \
OIM_DATABASE_CONNECTSTRING=$DB_HOST:$DB_PORT:$DB_SERVICE  \
MDS_USER_NAME=${OIM_SCHEMA_PREFIX}_MDS \
MDS_PASSWORD=$SCHEMA_PASSWORD \
SELECT_DIFFERENT_DATABASE_FOR_MDS=false \
OIM_SCHEMA_USER_NAME=${OIM_SCHEMA_PREFIX}_OIM \
OIM_SCHEMA_USER_PASSWORD=$DB_PASSWORD \
WEBLOGIC_ADMIN_SERVER_URL=t3://localhost:7001 \
WEBLOGIC_ADMINISTRATOR_USERNAME=weblogic \
WEBLOGIC_ADMINISTRATOR_PASSWORD=$DOMAIN_PASSWORD \
PROXY_URL_FOR_OIM=$OIM_FRONTEND_URL \
AS_HOST_NAME=`hostname` \
AS_PORT_NUMBER=$OIM_PORT  \
OIM_ADMINISTRATOR_PASSWORD=$OIM_ADMIN_PASSWORD \
CONFIRM_OIM_ADMINISTRATOR_PASSWORD=$OIM_ADMIN_PASSWORD \
KEYSTORE_PASSWORD=$DOMAIN_PASSWORD \
KEYSTORE_CONFIRM_PASSWORD=$DOMAIN_PASSWORD \
ENABLE_LDAP_SYNC=false

